force-app/main/default/objects/Cart__c/Cart__c.object-meta.xml
<CustomObject>
    <label>Cart</label>
    <nameField>
        <displayFormat>CART-{00000}</displayFormat>
        <label>Cart ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Carts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cart__c/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <label>List Price</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Cart__c/fields/PriceBookEntryID__c.field-meta.xml
<CustomField>
    <fullName>PriceBookEntryID__c</fullName>
    <label>PriceBookEntryID</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cart__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Carts</relationshipLabel>
    <relationshipName>Carts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cart__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quantity</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cart__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <label>Unit Price</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Pricebook_Setting__mdt/fields/PBRecordTypeId__c.field-meta.xml
<CustomField>
    <fullName>PBRecordTypeId__c</fullName>
    <label>PBRecordTypeId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FetchPriceBookProducts.cls
public with sharing class FetchPriceBookProducts {
    
    @AuraEnabled
    public static list<PricebookEntry> getProduts(){
        Pricebook_Setting__mdt retPriceBookId = [SELECT PBRecordTypeId__c from Pricebook_Setting__mdt where MasterLabel = 'RetailerPBRT'];
        
        list<PricebookEntry> products = [select Product2Id, Product2.Name, Product2.Description, UnitPrice, ProductCode from PricebookEntry where Pricebook2Id = :retPriceBookId.PBRecordTypeId__c];
        return products;
    }

    @AuraEnabled
    public static void clearCart(String AccountId){
        list<Cart__c> cart = [Select Account__c, Product__c, List_Price__c, Unit_Price__c, Quantity__c from Cart__c where Account__c =: AccountId];
        delete cart;
    }

    @AuraEnabled
    public static List<Cart__c> insertLineItem(String AccountId, String Product2Id, String PriceBookEntryId,Integer ListPrice, Integer UnitPrice, Integer Quantity){
        Cart__c cart = new Cart__c();
        cart.Account__c = AccountId;
        cart.Product__c = Product2Id;
        cart.PriceBookEntryID__c = PriceBookEntryId;
        cart.List_Price__c = UnitPrice;
        cart.Unit_Price__c = UnitPrice;
        cart.Quantity__c = Quantity;
        insert cart;

        return [Select Account__c, Product__c, List_Price__c, Unit_Price__c, Quantity__c from Cart__c where Account__c =: AccountId];
    }
}