src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>For Dealer Accounts</description>
        <label>Dealer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Retailer</fullName>
        <active>true</active>
        <description>For Retailer Accounts</description>
        <label>Retailer</label>
    </recordTypes>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders (Account)</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <defaultValue>IF($RecordType.Name = &#39;Dealer&#39; || $RecordType.Name = &#39;Retailer&#39;,&#39;SalesRep&#39;,&#39;DMS&#39;)</defaultValue>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DMS</fullName>
                </value>
                <value>
                    <fullName>Salesrep</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <label>Dealer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Retailer</fullName>
        <active>true</active>
        <label>Retailer</label>
    </recordTypes>
</CustomObject>

force-app/main/default/classes/TestOrderNotification.cls
/*
* Author:- Somesh Mamidwar
* Created:- 16-09-2020
* Last Updated:- Test Class for Order Notifications Class
* Description:- 
*/
@isTest
public class TestOrderNotification {

    @isTest Public static void trackOrder(){
        //Getting Dealer Account
        Account dealerAccnt = TestDataFactory.createDealerAccount();
        
        //Getting Retailer Account
        Account retailerAccnt = TestDataFactory.createRetailerAccount(dealerAccnt.Id);
        
        //retailerAccnt.Phone = '+919014630847';
        //update retailerAccnt;
        
        //Creating Product
        Product2 prod = TestDataFactory.createProduct('Test Fruit Juice');
        
        //Creating standard pricebook
        Id standardPb = Test.getStandardPricebookId();
        
        //Creating PricebookEntry
        PricebookEntry standardPrice = TestDataFactory.createPricebookEntry(100,prod.Id);
        
        Id orderRTRetlr = Schema.SObjectType.Order.getRecordTypeInfosByName().get('Retailer').getRecordTypeId();
        Order retailerOrder=TestDataFactory.createOrder(retailerAccnt.Id, orderRTRetlr);
        
        retailerOrder.Account__c=dealerAccnt.Id;
        
        update retailerOrder;
        
        retailerOrder.Status = 'Approval Request';
        update retailerOrder;

        retailerOrder.Status = 'Booked';
        update retailerOrder;
        
         retailerOrder.Status = 'Out For Delivery';
        update retailerOrder;          
        
        retailerOrder.Status = 'Delivered';
        update retailerOrder;
        
        
        Id orderDealerRecTypId = Schema.SObjectType.Order.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
        Order dealerOrder=TestDataFactory.createOrder(dealerAccnt.Id, orderDealerRecTypId);
        
        dealerOrder.Status = 'Confirmed';
        dealerOrder.Channel__c = 'SalesRep';
        update dealerOrder;
        
    }
    
}