src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>For Dealer Accounts</description>
        <label>Dealer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Retailer</fullName>
        <active>true</active>
        <description>For Retailer Accounts</description>
        <label>Retailer</label>
    </recordTypes>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Discount_Amount__c</fullName>
        <label>Discount Amount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Header_Discount__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Header Discount</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <label>Dealer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Retailer</fullName>
        <active>true</active>
        <label>Retailer</label>
    </recordTypes>
</CustomObject>

force-app/main/default/objects/Order/fields/Applied_Offer__c.field-meta.xml
<CustomField>
    <fullName>Applied_Offer__c</fullName>
    <label>Applied Offer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Scheme__c.field-meta.xml
<CustomField>
    <fullName>Scheme__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Scheme</label>
    <referenceTo>Scheme__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>Applied_Offer__c</fullName>
        <label>Applied Offer</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Discount_Amount__c</fullName>
        <label>Discount Amount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

src/objects/Scheme__c.object
<CustomObject>
    <label>Scheme</label>
    <nameField>
        <label>Scheme Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schemes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Buy__c</fullName>
        <label>Buy</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Discount_Amount__c</fullName>
        <label>Discount Amount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Discount_Type__c</fullName>
        <label>Discount Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Amount</fullName>
                    <default>true</default>
                    <label>Amount</label>
                </value>
                <value>
                    <fullName>Percentage</fullName>
                </value>
                <value>
                    <fullName>Quantity</fullName>
                </value>
                <value>
                    <fullName>Coupon</fullName>
                </value>
                <value>
                    <fullName>Cross Product Offer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Get_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Get Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Schemes (Get Product)</relationshipLabel>
        <relationshipName>Schemes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Get__c</fullName>
        <label>Get</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Header_Discount__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Header Discount</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order_Amount__c</fullName>
        <label>Order Amount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Schemes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scheme_Type__c</fullName>
        <label>Scheme Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Generic</fullName>
                </value>
                <value>
                    <fullName>Specific</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Andhra Pradesh</fullName>
                </value>
                <value>
                    <fullName>Arunachal Pradesh</fullName>
                </value>
                <value>
                    <fullName>Assam</fullName>
                </value>
                <value>
                    <fullName>Bihar</fullName>
                </value>
                <value>
                    <fullName>Chhattisgarh</fullName>
                </value>
                <value>
                    <fullName>Goa</fullName>
                </value>
                <value>
                    <fullName>Gujarat</fullName>
                </value>
                <value>
                    <fullName>Haryana</fullName>
                </value>
                <value>
                    <fullName>Himachal Pradesh</fullName>
                </value>
                <value>
                    <fullName>Jharkhand</fullName>
                </value>
                <value>
                    <fullName>Karnataka</fullName>
                </value>
                <value>
                    <fullName>Kerala</fullName>
                </value>
                <value>
                    <fullName>Madhya Pradesh</fullName>
                </value>
                <value>
                    <fullName>Maharashtra</fullName>
                </value>
                <value>
                    <fullName>Manipur</fullName>
                </value>
                <value>
                    <fullName>Meghalaya</fullName>
                </value>
                <value>
                    <fullName>Mizoram</fullName>
                </value>
                <value>
                    <fullName>Odisha</fullName>
                </value>
                <value>
                    <fullName>Punjab</fullName>
                </value>
                <value>
                    <fullName>Rajasthan</fullName>
                </value>
                <value>
                    <fullName>Sikkim</fullName>
                </value>
                <value>
                    <fullName>Tamil Nadu</fullName>
                </value>
                <value>
                    <fullName>Telangana</fullName>
                </value>
                <value>
                    <fullName>Tripura</fullName>
                </value>
                <value>
                    <fullName>Uttarakhand</fullName>
                </value>
                <value>
                    <fullName>Uttar Pradesh</fullName>
                </value>
                <value>
                    <fullName>West Bengal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Approval Request</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/classes/TestApplyOrderLineItemOffers.cls
@isTest
public class TestApplyOrderLineItemOffers {

 

     @isTest Public static void lineOffersQuantityCheck() {
        
        //Getting Dealer Account
        Account dealerAccnt = TestDataFactory.createDealerAccount();
        
        //Getting Retailer Account
        Account retailerAccnt = TestDataFactory.createRetailerAccount(dealerAccnt.Id);

 

        //Creating Product
        Product2 prod = TestDataFactory.createProduct('Test Fruit Juice');

 

        //Creating PricebookEntry
        PricebookEntry standardPrice = TestDataFactory.createPricebookEntry(100,prod.Id);

 

        // Creating Qunatity Scheme
        Id schemeRecTypId = Schema.SObjectType.Scheme__c.getRecordTypeInfosByName().get('Quantity Discount').getRecordTypeId();
        Scheme__c sch =new Scheme__c();
        sch.Name = 'Buy 100 Get 10 for Test Product';
        sch.RecordTypeId = schemeRecTypId;
        sch.Active__c=True;
        sch.Start_Date__c = system.today()-10;
        sch.End_Date__c=system.today()+20;
        sch.Scheme_Type__c='Specific';
        sch.Discount_Type__c='Quantity';
        sch.Product__c=prod.Id;   
        sch.Buy__c=100;
        sch.Get__c=10;
        sch.Status__c='Approved';
        sch.Active__c=true;
        sch.State__c='Telangana';
        insert sch;

      /*  Id offerPerRecId = Schema.SObjectType.Scheme__c.getRecordTypeInfosByName().get('Amount Discount').getRecordTypeId();
        
        Scheme__c offerAmount =new Scheme__c(RecordTypeId=offerPerRecId,Name='Buy7000aboveGet700back',Start_Date__c=system.today()-30,Active__c=True);
        insert offerAmount;
        offerAmount.End_Date__c=system.today()+30;
        offerAmount.Scheme_Type__c='Specific';
        offerAmount.Order_Amount__c=7000;
        offerAmount.Discount_Type__c='Amount';
        offerAmount.Discount_Amount__c=700;   
        //offerAmount.End_Date__c=system.today()+20;
        offerAmount.Header_Discount__c=True;
        offerAmount.Status__c='Approved';
        offerAmount.Active__c=true;
        offerAmount.State__c='Telangana';
        update offerAmount;*/

        //Creating Retailer Order
        Id retOrdRecTypId = Schema.SObjectType.Order.getRecordTypeInfosByName().get('Retailer').getRecordTypeId();    
        
        Order retailerOrder = TestDataFactory.createOrder(retailerAccnt.Id, retOrdRecTypId);

 

        //Creating Order Item
        OrderItem oi=new OrderItem(Product2Id=prod.Id,Quantity=100,OrderId=retailerOrder.id,UnitPrice=100,ListPrice=100,PricebookEntryId=standardPrice.id);
        insert oi;
 
 
       // System.debug('discount is'+oi.)
           OrderItem newOi = [select Id,Quantity from OrderItem where Id = :oi.Id];
        System.debug('Order Item Quantity is'+newOi.Quantity);
        System.assertEquals(110,newOi.Quantity);
        
 

    }
    
    @isTest Public static void lineOffersCrossProductCheck() {
        
        //Getting Dealer Account
        Account dealerAccnt = TestDataFactory.createDealerAccount();
        
        //Getting Retailer Account
        Account retailerAccnt = TestDataFactory.createRetailerAccount(dealerAccnt.Id);

 

        //Creating Products
        Product2 prod1 = TestDataFactory.createProduct('Test Fruit Juice1');
        
        Product2 prod2 = TestDataFactory.createProduct('Test Fruit Juice2');

 

        //Creating PricebookEntrys
        PricebookEntry standardPrice = TestDataFactory.createPricebookEntry(100,prod1.Id);
        
        PricebookEntry standardPrice1 = TestDataFactory.createPricebookEntry(100,prod2.Id);

 

        // Creating CrossProduct Scheme
        Id schemeRecTypId = Schema.SObjectType.Scheme__c.getRecordTypeInfosByName().get('Cross Product Offer').getRecordTypeId();
        Scheme__c sch =new Scheme__c();
        sch.Name = 'Buy 100 Test Fruit Juice1 Get 10 Test Fruit Juice2';
        sch.RecordTypeId = schemeRecTypId;
        sch.Active__c=True;
        sch.Start_Date__c = system.today()-10;
        sch.End_Date__c = system.today()+20;
        sch.Scheme_Type__c = 'Specific';
        sch.Discount_Type__c='Cross Product Offer';
        sch.Product__c = prod1.Id;
        sch.Get_Product__c= prod2.Id;        
        sch.Buy__c=100;
        sch.Get__c=10;
        sch.Status__c='Approved';
        sch.Active__c=true;
        sch.State__c='Telangana';

 

        insert sch;

 

        //Creating Retailer Order
        Id retOrdRecTypId = Schema.SObjectType.Order.getRecordTypeInfosByName().get('Retailer').getRecordTypeId();    
        
        Order retailerOrder = TestDataFactory.createOrder(retailerAccnt.Id, retOrdRecTypId);

 

        //Creating Order Item
        OrderItem oi=new OrderItem(Product2Id=prod1.Id,Quantity=100,OrderId=retailerOrder.id,UnitPrice=100,ListPrice=100,PricebookEntryId=standardPrice.id);
        insert oi;

 

           OrderItem newOi = [select Id,Quantity from OrderItem where Product2Id = :prod2.Id and OrderId = :retailerOrder.id];
        System.debug('Order Item Quantity is'+newOi.Quantity);
        System.assertEquals(10,newOi.Quantity);

 

    }
    @isTest Public static void lineOffersAmountCheck() {
        
        //Getting Dealer Account
        Account dealerAccnt = TestDataFactory.createDealerAccount();
        
        //Getting Retailer Account
        Account retailerAccnt = TestDataFactory.createRetailerAccount(dealerAccnt.Id);

 

        //Creating Product
        Product2 prod = TestDataFactory.createProduct('Test Fruit Juice');

 

        //Creating PricebookEntry
        PricebookEntry standardPrice = TestDataFactory.createPricebookEntry(100,prod.Id);
       
        
        
        Id offerPerRecId = Schema.SObjectType.Scheme__c.getRecordTypeInfosByName().get('Amount Discount').getRecordTypeId();
        
        
        // Creating Qunatity Scheme
        Id schemeRecTypId = Schema.SObjectType.Scheme__c.getRecordTypeInfosByName().get('Quantity Discount').getRecordTypeId();
        Scheme__c sch =new Scheme__c();
        sch.Name = 'Buy 100 Get 10 for Test Product';
        sch.RecordTypeId = schemeRecTypId;
        sch.Active__c=True;
        sch.Start_Date__c = system.today()-10;
        sch.End_Date__c=system.today()+20;
        sch.Scheme_Type__c='Specific';
        sch.Discount_Type__c='Quantity';
        sch.Product__c=prod.Id;   
        sch.Buy__c=100;
        sch.Get__c=10;
        sch.Status__c='Approved';
        sch.Active__c=true;
        sch.State__c='Telangana';
        insert sch;
        //amount Scheme
        Scheme__c offerAmount =new Scheme__c();        
        //offerAmount.
        offerAmount.Name='Buy7000aboveGet700back';
        offerAmount.Start_Date__c=system.today()-30;
        offerAmount.RecordTypeId=offerPerRecId;
        offerAmount.End_Date__c=system.today()+30;
        offerAmount.Scheme_Type__c='Specific';
        offerAmount.Order_Amount__c=7000;
        offerAmount.Discount_Type__c='Amount';
        offerAmount.Discount_Amount__c=700;         
        offerAmount.Header_Discount__c=True;
        offerAmount.Status__c='Approved';
        offerAmount.Active__c=true;
        offerAmount.State__c='Telangana';
        offerAmount.Product__c=prod.id;
        insert offerAmount;

        //Creating Retailer Order
        Id retOrdRecTypId = Schema.SObjectType.Order.getRecordTypeInfosByName().get('Retailer').getRecordTypeId();    
        
        Order retailerOrder = TestDataFactory.createOrder(retailerAccnt.Id, retOrdRecTypId);

 

        //Creating Order Item
        OrderItem oi=new OrderItem(Product2Id=prod.Id,Quantity=70,OrderId=retailerOrder.id,UnitPrice=100,ListPrice=100,PricebookEntryId=standardPrice.id);
        insert oi;
 
 		Order retOrd=[SELECT Discount_Amount__c FROM Order WHERE id=:retailerOrder.id];
        System.debug('From Amount ..discount is'+retOrd.Discount_Amount__c);
           OrderItem newOi = [select Id,Quantity,Applied_Offer__c from OrderItem where Id = :oi.Id];
        System.debug('From Amount sOrder Item Quantity is'+newOi.Quantity);
        //System.assertEquals('Buy7000aboveGet700back',retOrd.Applied_Offer__c);
        
 

    }
    
    
    
}