src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Credit_Limit__c</fullName>
        <label>Credit Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>For Dealer Accounts</description>
        <label>Dealer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Retailer</fullName>
        <active>true</active>
        <description>For Retailer Accounts</description>
        <label>Retailer</label>
    </recordTypes>
</CustomObject>

src/objects/Inventory__c.object
<CustomObject>
    <description>Inventory is used to manage warehouse stock activities,order related activities etc</description>
    <label>Inventory</label>
    <nameField>
        <displayFormat>INV-{00000}</displayFormat>
        <label>Inventory Id Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Current_OnHand_Qty__c</fullName>
        <description>Quantity which is left over after receiving and shipping</description>
        <formula>((OnHand_Qty__c + Receivable_Qty__c ) - Shipment_Quantity__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Quantity which is left over after receiving and shipping</inlineHelpText>
        <label>Quantity Available</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Dealer_Product_Price__c</fullName>
        <description>Product Price of Dealer Price Book</description>
        <label>Dealer Product Price</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Distributor__c</fullName>
        <label>Distributor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Inventories</relationshipLabel>
        <relationshipName>Inventories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>OnHand_Qty__c</fullName>
        <inlineHelpText>which is available at warehouse</inlineHelpText>
        <label>Quantity On Hand</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select the Related Pricebook</inlineHelpText>
        <label>Price Book</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Inventories</relationshipLabel>
        <relationshipName>Inventories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relationship with Product object to access product fields</description>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Inventories</relationshipLabel>
        <relationshipName>Inventories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Receivable_Qty__c</fullName>
        <label>Receivable Receipt</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Retailer_Price_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is retailer price book</description>
        <label>Retailer Price Book</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Inventories (Retailer Price Book)</relationshipLabel>
        <relationshipName>Inventories1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Retailer_Price__c</fullName>
        <description>Retailer price</description>
        <label>Retailer Product Price</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Shipment_Quantity__c</fullName>
        <inlineHelpText>Enter the Quantity to be Shipped</inlineHelpText>
        <label>Planned Shipments</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders (Account)</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Estimated_Delivery_Date__c</fullName>
        <label>Estimated Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Shipment_Date__c</fullName>
        <label>Shipment_Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <label>Dealer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Retailer</fullName>
        <active>true</active>
        <label>Retailer</label>
    </recordTypes>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Inventory__c</fullName>
        <label>Inventory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Stock</fullName>
                    <default>true</default>
                    <label>In Stock</label>
                </value>
                <value>
                    <fullName>Limited Availability</fullName>
                </value>
                <value>
                    <fullName>Out of Stock</fullName>
                </value>
                <value>
                    <fullName>On Backorder</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Max_Qty__c</fullName>
        <description>The Maximum Quantity of Products</description>
        <label>Maximum Qty</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Min_Qty__c</fullName>
        <description>The Minimum Quantity of Products</description>
        <label>Minimum Qty</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Classification__c</fullName>
        <label>Product Classification</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/classes/TestsInventory.cls
@isTest public with sharing class TestsInventory {
    //public TestsInventory() {

    //}
    //@isTest(seeAllData=true) 
//public class Test_InventoryTrigger 
//{   
    @isTest public Static void InventoryRetcheck()
    {
        //Distributor Account
        RecordType AccRTDist = [SELECT Id FROM RecordType WHERE sObjectType = 'Account' AND Name = 'Dealer'];
        Account DistAcc=new Account(Name='Gaja',recordTypeId=AccRTDist.id,Credit_Limit__c=20000);
        insert DistAcc;        
        //retailer account
        RecordType AccRTRet=[SELECT Id FROM RecordType WHERE sObjectType = 'Account' AND Name = 'Retailer'];
        Account RetailerAcc=new Account(Name='shiva',ParentId=DistAcc.id,recordTypeId=AccRTRet.id);
        insert RetailerAcc;//'0122v000002AYRFAA4'
        //product
        Product2 painbalm=new Product2(Name='Pain Balm',Family='Pain Management',Product_Classification__c='A',IsActive=true);
        painbalm.Max_Qty__c=300;
        painbalm.Min_Qty__c=180;
        insert painbalm;
        //standard pricebook
        //Pricebook2 standardPBook = [select id from Pricebook2 where isStandard=true limit 1];
        Id standardPBook=Test.getStandardPricebookId();
        PricebookEntry standardPrice = new PricebookEntry(Pricebook2Id = standardPBook, Product2Id = painbalm.id, UnitPrice = 100, IsActive = true, UseStandardPrice = false);//'01s2v00000L2BllAAF'
        insert standardPrice;
        //dealer pricebook
        Pricebook2 standardPb=new Pricebook2(Name='Dealer',IsActive=true);//standardPb.IsStandard=true;
        insert standardPb;
        //dealer pricebook entry
        PricebookEntry DstandardPrice = new PricebookEntry();
        DstandardPrice.Pricebook2Id = standardPb.Id;
        DstandardPrice.Product2Id = painbalm.Id;
        DstandardPrice.UnitPrice = 100;
        DstandardPrice.IsActive = true;
        DstandardPrice.UseStandardPrice = false;
        insert DstandardPrice;
        
        //retailer pricebook
        Pricebook2 RetailerPb=new Pricebook2(Name='Retailer',IsActive=true);
        insert RetailerPb;
        //retailer pricebook entry
        PricebookEntry retailerPbEntry = new PricebookEntry();
        retailerPbEntry.Pricebook2Id = RetailerPb.id;
        retailerPbEntry.Product2Id = painbalm.id;
        retailerPbEntry.UnitPrice = 150;
        retailerPbEntry.IsActive = true;
        retailerPbEntry.UseStandardPrice = false;
        insert retailerPbEntry ;
        
        //Inventory creation
        Inventory__c newInv=new Inventory__c(Distributor__c=DistAcc.Id,Product__c=painbalm.Id);
        //insert newInv;        
        newInv.Distributor__c=DistAcc.id;
        newInv.OnHand_Qty__c=200;
        newInv.Product__c=painbalm.id;
        newInv.Price_Book__c=standardPb.id;//dealer pricebook
        newInv.Dealer_Product_Price__c=DstandardPrice.UnitPrice;
        
        newInv.Retailer_Price_Book__c=RetailerPb.id;//retailer pricebook
        newInv.Retailer_Price__c=retailerPbEntry.UnitPrice;
        insert newInv;
        system.debug('inventory values are'+newInv);
        

        
        //Test Order Insert
        //creating retailer order
        RecordType orderRTRet=[SELECT Id FROM RecordType WHERE sObjectType = 'Order' AND Name = 'Retailer'];
        
        Order o = new Order();
        o.Name = 'Test Order ';
        o.Status = 'Draft';
        o.RecordTypeId=orderRTRet.id;
        o.EffectiveDate = system.today();
        //o.EndDate = system.today() + 4;
        o.AccountId = RetailerAcc.id;
        o.Pricebook2Id = RetailerPb.Id ;
        o.Shipment_Date__c=system.today()+10;
        o.Estimated_Delivery_Date__c=system.today()+11;
        
        // o.icxdms__Order_Price_Book__c=RetailerPb.id;
        insert o;o.Account__c=DistAcc.Id;update o;
        system.debug('pb11 id issssssssssss'+o.Pricebook2Id);
        system.debug('pb id issssssssssssrtyu'+RetailerPb.Id);
        
        // PriceBookEntry pbe = [SELECT id FROM PricebookEntry 
        //WHERE Product2Id =: painbalm.id AND Pricebook2Id =: RetailerPb.Id];
        //system.debug('pb entry id is'+pbe);Pricebookentry entry = [SELECT Id,unitprice FROM PricebookEntry WHERE Pricebook2Id = :standardBook.Id AND Product2.ProductCode = 'ALW'];
        
        OrderItem i = new OrderItem();       
        i.OrderId = o.id;
        i.Product2id = painbalm.id;
        i.PricebookEntryId=retailerPbEntry.Id;//standardPBook.id;//pbe.Id ;//standardPrice.id;
        i.Quantity = 25;//i.icxdms__Order_Record_Type__c=orderRTRet.id;
        i.UnitPrice = 100;    
        /* try{
insert i;
}
catch (Exception e)
{
e.getMessage();
}*/        insert i; 
        system.debug('values insertdsfasd are'+i);
        //system.assertEquals(2500,o.TotalAmount);
        o.Status='Booked';
        update o;
        // system.debug('pb id issssssssssssrtyu'+standardPBook.id);
        
        //system.assertEquals(RetailerPb.id,o.Pricebook2Id,'aaaaaaaaaaaaaaaaaachecking price book was modified after it was inserted');
        
        //system.debug('onhand quantity is'+newInv.icxdms__Current_OnHand_Qty__c);
        //System.assertEquals(100,standardPrice.UnitPrice);        
        //System.assertEquals(100,newInv.icxdms__Product_Price__c);
        System.assertEquals(null,newInv.Current_OnHand_Qty__c);//175
        
        if(o.Status=='Booked'){
            system.debug('i am booked');
            System.assertEquals(null,newInv.Shipment_Quantity__c);//25
        }
        //update o;
        o.Status='Out for delivery';
        //upsert o;
        if(o.Status=='Out for delivery')
        {
            if(o.AccountId==RetailerAcc.id && o.RecordTypeId==orderRTRet.id)
            {
                Account ordAcc = [Select Id,ParentId from Account where Id =:RetailerAcc.id];
                String sDistributorId = ordAcc.ParentId;
                
            }
            System.assertEquals(200,newInv.OnHand_Qty__c);
            
        }
        // System.assertEquals(175,newInv.icxdms__Current_OnHand_Qty__c);
        
        
    }
     @isTest public Static void InventoryRetcheckOutforDelivery()
    {
        //Distributor Account
        RecordType AccRTDist = [SELECT Id FROM RecordType WHERE sObjectType = 'Account' AND Name = 'Dealer'];
        Account DistAcc=new Account(Name='Gaja',recordTypeId=AccRTDist.id,Credit_Limit__c=20000);
        insert DistAcc;        
        //retailer account
        RecordType AccRTRet=[SELECT Id FROM RecordType WHERE sObjectType = 'Account' AND Name = 'Retailer'];
        Account RetailerAcc=new Account(Name='shiva',ParentId=DistAcc.id,recordTypeId=AccRTRet.id);
        insert RetailerAcc;//'0122v000002AYRFAA4'
        //product
        Product2 painbalm=new Product2(Name='Pain Balm',Family='Pain Management',Product_Classification__c='A',IsActive=true);
        painbalm.Max_Qty__c=300;
        painbalm.Min_Qty__c=180;
        insert painbalm;
        //standard pricebook
       // Pricebook2 standardPBook = [select id from Pricebook2 where isStandard=true limit 1];
        Id standardPBook =Test.getStandardPricebookId();
        PricebookEntry standardPrice = new PricebookEntry(Pricebook2Id = standardPBook, Product2Id = painbalm.id, UnitPrice = 100, IsActive = true, UseStandardPrice = false);//'01s2v00000L2BllAAF'
        insert standardPrice;
        //dealer pricebook
        Pricebook2 standardPb=new Pricebook2(Name='Dealer',IsActive=true);//standardPb.IsStandard=true;
        insert standardPb;
        //dealer pricebook entry
        PricebookEntry DstandardPrice = new PricebookEntry();
        DstandardPrice.Pricebook2Id = standardPb.Id;
        DstandardPrice.Product2Id = painbalm.Id;
        DstandardPrice.UnitPrice = 100;
        DstandardPrice.IsActive = true;
        DstandardPrice.UseStandardPrice = false;
        insert DstandardPrice;
 
        //retailer pricebook
        Pricebook2 RetailerPb=new Pricebook2(Name='Retailer',IsActive=true);
        insert RetailerPb;
        //retailer pricebook entry
        PricebookEntry retailerPbEntry = new PricebookEntry();
        retailerPbEntry.Pricebook2Id = RetailerPb.id;
        retailerPbEntry.Product2Id = painbalm.id;
        retailerPbEntry.UnitPrice = 150;
        retailerPbEntry.IsActive = true;
        retailerPbEntry.UseStandardPrice = false;
        insert retailerPbEntry ;
        
        //Inventory creation
        Inventory__c newInv=new Inventory__c(Distributor__c=DistAcc.Id,Product__c=painbalm.Id);
        //insert newInv;        
        newInv.Distributor__c=DistAcc.id;
        newInv.OnHand_Qty__c=200;
        newInv.Product__c=painbalm.id;
        newInv.Price_Book__c=standardPb.id;//dealer pricebook
        newInv.Dealer_Product_Price__c=DstandardPrice.UnitPrice;
        
        newInv.Retailer_Price_Book__c=RetailerPb.id;//retailer pricebook
        newInv.Retailer_Price__c=retailerPbEntry.UnitPrice;
        insert newInv;
        system.debug('inventory values are'+newInv);
        system.debug('forupdate inventory');
        
        //newInv.icxdms__Product_Price__c=standardPBook.UnitPrice;
        newInv.Retailer_Price__c=retailerPbEntry.UnitPrice;
        update newInv;
        //Test Order Insert
        //creating retailer order
        RecordType orderRTRet=[SELECT Id FROM RecordType WHERE sObjectType = 'Order' AND Name = 'Retailer'];
        
        Order o = new Order();
        o.Name = 'Test Order ';
        o.Status = 'Draft';
        o.RecordTypeId=orderRTRet.id;
        o.EffectiveDate = system.today();
        //o.EndDate = system.today() + 4;
        o.AccountId = RetailerAcc.id;
        o.Pricebook2Id = RetailerPb.Id ;
        o.Shipment_Date__c=system.today()+10;
        o.Estimated_Delivery_Date__c=system.today()+11;
        
        // o.icxdms__Order_Price_Book__c=RetailerPb.id;
        insert o;o.Account__c=DistAcc.Id;update o;
        system.debug('pb11 id issssssssssss'+o.Pricebook2Id);
        system.debug('pb id issssssssssssrtyu'+RetailerPb.Id);
        
        // PriceBookEntry pbe = [SELECT id FROM PricebookEntry 
        //WHERE Product2Id =: painbalm.id AND Pricebook2Id =: RetailerPb.Id];
        //system.debug('pb entry id is'+pbe);Pricebookentry entry = [SELECT Id,unitprice FROM PricebookEntry WHERE Pricebook2Id = :standardBook.Id AND Product2.ProductCode = 'ALW'];
        
        OrderItem i = new OrderItem();       
        i.OrderId = o.id;
        i.Product2id = painbalm.id;
        i.PricebookEntryId=retailerPbEntry.Id;//standardPBook.id;//pbe.Id ;//standardPrice.id;
        i.Quantity = 25;//i.icxdms__Order_Record_Type__c=orderRTRet.id;
        i.UnitPrice = 100;    
        /* try{
insert i;
}
catch (Exception e)
{
e.getMessage();
}*/        insert i; 
        system.debug('values insertdsfasd are'+i);
        //system.assertEquals(2500,o.TotalAmount);
        o.Status='Booked';
        update o;
        // system.debug('pb id issssssssssssrtyu'+standardPBook.id);
        
        //system.assertEquals(RetailerPb.id,o.Pricebook2Id,'aaaaaaaaaaaaaaaaaachecking price book was modified after it was inserted');
        
        //system.debug('onhand quantity is'+newInv.icxdms__Current_OnHand_Qty__c);
        //System.assertEquals(100,standardPrice.UnitPrice);        
        //System.assertEquals(100,newInv.icxdms__Product_Price__c);
        System.assertEquals(null,newInv.Current_OnHand_Qty__c);//175
        
        if(o.Status=='Booked'){
            system.debug('i am booked');
            System.assertEquals(null,newInv.Shipment_Quantity__c);//25
        }
        //update o;
        //o.icxdms__Planned_Shipment_Date__c=system.today()+10;
        //o.icxdms__Estimated_Delivery_Date__c=system.today()+11;
        //o.icxdms__Deliverd_Date__c=system.today()+12;
        // o;
        o.Status='Out For Delivery';update o;
                if(o.Status=='Out For Delivery')
                {
                    system.debug('STATUS IS i am out for delivery '+o.Status);}

        //upsert o;
        if(o.Status=='Out For Delivery')
        {
           /* if(o.AccountId==RetailerAcc.id && o.RecordTypeId==orderRTRet.id)
            {
                Account ordAcc = [Select Id,ParentId from Account where Id =:RetailerAcc.id];
                String sDistributorId = ordAcc.ParentId;
                
            }*/
            System.assertEquals(200,newInv.OnHand_Qty__c);
                        System.assertEquals(null,newInv.Shipment_Quantity__c);//25

            
        }
         System.assertEquals(null,newInv.Current_OnHand_Qty__c);
        
        
    }
    
   
    
    @isTest public Static void CheckDistInventory(){
        //Distributor Account
        RecordType AccRTDist = [SELECT Id FROM RecordType WHERE sObjectType = 'Account' AND Name = 'Dealer'];
        Account DistAcc=new Account(Name='Gaja',recordTypeId=AccRTDist.id,Credit_Limit__c=20000);
        insert DistAcc;        
        //product
        Product2 painbalm=new Product2(Name='Pain Balm',Family='Pain Management',Product_Classification__c='A',IsActive=true);
        painbalm.Max_Qty__c=300;
        painbalm.Min_Qty__c=180;
        insert painbalm;
        //standard pricebook
        //Pricebook2 standardPBook = [select id from Pricebook2 where isStandard=true limit 1];
        Id standardPBook=Test.getStandardPricebookId();
        PricebookEntry standardPrice = new PricebookEntry(Pricebook2Id = standardPBook, Product2Id = painbalm.id, UnitPrice = 100, IsActive = true, UseStandardPrice = false);//'01s2v00000L2BllAAF'
        insert standardPrice;
        //dealer pricebook
        Pricebook2 standardPb=new Pricebook2(Name='Dealer',IsActive=true);//standardPb.IsStandard=true;
        insert standardPb;
        //dealer pricebook entry
        PricebookEntry DtandardPrice = new PricebookEntry();
        DtandardPrice.Pricebook2Id = standardPb.Id;
        DtandardPrice.Product2Id = painbalm.Id;
        DtandardPrice.UnitPrice = 100;
        DtandardPrice.IsActive = true;
        DtandardPrice.UseStandardPrice = false;
        insert DtandardPrice;
        //Inventory creation
        Inventory__c newInv=new Inventory__c(Distributor__c=DistAcc.Id,Product__c=painbalm.Id);
        //insert newInv;        
        newInv.Distributor__c=DistAcc.id;
        newInv.OnHand_Qty__c=200;
        newInv.Product__c=painbalm.id;
        newInv.Price_Book__c=standardPb.id;//dealer pricebook
        newInv.Dealer_Product_Price__c=DtandardPrice.UnitPrice;
        
        //newInv.icxdms__Retailer_Price_Book__c=RetailerPb.id;//retailer pricebook
        //newInv.icxdms__Retailer_Price__c=retailerPbEntry.UnitPrice;
        insert newInv;
        RecordType dealordrt=[SELECT Id FROM RecordType WHERE sObjectType = 'Order' AND Name = 'Dealer'];
        
        //creating dealer order
        Order o = new Order();
        o.Name = 'Test Order ';
        o.Status = 'Draft';
        o.EffectiveDate = system.today();
        o.RecordTypeId=dealordrt.id;
        //o.EndDate = system.today() + 4;
        o.AccountId = DistAcc.id;
        o.Pricebook2Id = standardPb.Id ;
        o.Shipment_Date__c=system.today()+10;
        o.Estimated_Delivery_Date__c=system.today()+11;        
        insert o;        
        OrderItem i = new OrderItem();
        i.OrderId = o.id;
        i.Product2id = painbalm.id;
        i.PricebookEntryId=DtandardPrice.Id;
        i.Quantity = 25;
        i.UnitPrice = 100;    
        insert i;
        System.debug('inserted order id is'+i);
        
        o.Status = 'Confirmed';update o;
        if(o.Status == 'Confirmed') {
            Inventory__c invFields=[SELECT Receivable_Qty__c FROM Inventory__c WHERE id=:newInv.id];
            System.assertEquals(225,invFields.Receivable_Qty__c);
        }
    }
}