src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Credit_Limit__c</fullName>
        <label>Credit Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Partner_Dealer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Dealer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>For Dealer Accounts</description>
        <label>Dealer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Retailer</fullName>
        <active>true</active>
        <description>For Retailer Accounts</description>
        <label>Retailer</label>
    </recordTypes>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders (Account)</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Dealer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Dealer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <label>Dealer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Retailer</fullName>
        <active>true</active>
        <label>Retailer</label>
    </recordTypes>
</CustomObject>

force-app/main/default/classes/TestSaccountTrigger.cls
@isTest 
public with sharing class TestSaccountTrigger {
    Public Static testMethod void checkAccount(){
        RecordType accRTDist=[SELECT Id FROM RecordType WHERE sObjectType = 'Account' AND Name = 'Dealer'];
        //distributor account
        Account distacc=new Account(Name='Gajendra',recordTypeId=accRTDist.id,Credit_Limit__c=3000);
        insert distacc;
        String distAccID=distacc.id;
        //distibutor contact
        Contact c=new Contact(FirstName='Agarwal',LastName='Manish',AccountId=distAccID);
        
        RecordType accRTRet=[SELECT Id FROM RecordType WHERE sObjectType = 'Account' AND Name = 'Retailer'];
        //retailer account
        Account retailerAcc=new Account(Name='shiva',ParentId=distAccID,recordTypeId=accRTRet.id);
        insert retailerAcc;//'0122v000002AYRFAA4'
        //retailer order
        Order retOrder=new Order(AccountId=retailerAcc.Id,Status='Draft',EffectiveDate=system.today()-6);//,RecordTypeId=dealrOrdRT.id
        insert retOrder;
        String accFields = GetAllFields.getAllObjectField('Account');
        String query = 'select ' + accFields + ' from Account Where Id = \''+ retOrder.AccountId +'\' Limit 1';
        retOrder.Account__c = retailerAcc.ParentId;
        query = 'select ' + accFields + ' from Account Where Id = \''+ retailerAcc.ParentId +'\' Limit 1';
        Account parAccount = Database.query(query);
        //retOrder.Partner_Dealer__c = parAccount.Partner_Dealer__c;
        system.debug('I am Query V'+parAccount);
        String v1 = 'assert';
        retailerAcc.ParentId=distacc.id;
        update retailerAcc;
        //Order OrdFields=[SELECT Partner_Dealer__c FROM Order WHERE id=:retOrder.id];
        Account acFields=[SELECT Partner_Dealer__c FROM Account WHERE id=:retailerAcc.id];
        System.assertEquals('Gajendra',parAccount.Name,v1);
        //System.assertEquals('Gajendra',acFields.Partner_Dealer__c,v1);
        System.debug('checking for assert');
        
    }
}