src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>For Dealer Accounts</description>
        <label>Dealer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Retailer</fullName>
        <active>true</active>
        <description>For Retailer Accounts</description>
        <label>Retailer</label>
    </recordTypes>
</CustomObject>

src/objects/Coupon__c.object
<CustomObject>
    <label>Coupon</label>
    <nameField>
        <label>Coupon Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coupons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Valid_From__c</fullName>
        <label>Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Valid_To__c</fullName>
        <label>Valid To</label>
        <type>Date</type>
    </fields>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders (Account)</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Discount_Amount__c</fullName>
        <label>Discount Amount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Header_Discount__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Header Discount</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <label>Dealer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Retailer</fullName>
        <active>true</active>
        <label>Retailer</label>
    </recordTypes>
</CustomObject>

force-app/main/default/objects/Order/fields/Applied_Offer__c.field-meta.xml
<CustomField>
    <fullName>Applied_Offer__c</fullName>
    <label>Applied Offer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Scheme__c.field-meta.xml
<CustomField>
    <fullName>Scheme__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Scheme</label>
    <referenceTo>Scheme__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>Applied_Offer__c</fullName>
        <label>Applied Offer</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Discount_Amount__c</fullName>
        <label>Discount Amount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

src/objects/Scheme__c.object
<CustomObject>
    <label>Scheme</label>
    <nameField>
        <label>Scheme Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schemes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Coupon__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Coupon</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Coupon__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Coupon__c.Valid_From__c</field>
                <operation>lessOrEqual</operation>
                <valueField>$Source.CreatedDate</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Coupon__c</referenceTo>
        <relationshipLabel>Schemes</relationshipLabel>
        <relationshipName>Schemes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Discount_Amount__c</fullName>
        <label>Discount Amount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Discount_Percentage__c</fullName>
        <label>Discount Percentage</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Discount_Type__c</fullName>
        <label>Discount Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Amount</fullName>
                    <default>true</default>
                    <label>Amount</label>
                </value>
                <value>
                    <fullName>Percentage</fullName>
                </value>
                <value>
                    <fullName>Quantity</fullName>
                </value>
                <value>
                    <fullName>Coupon</fullName>
                </value>
                <value>
                    <fullName>Cross Product Offer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Header_Discount__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Header Discount</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order_Amount__c</fullName>
        <label>Order Amount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Scheme_Type__c</fullName>
        <label>Scheme Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Generic</fullName>
                </value>
                <value>
                    <fullName>Specific</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Andhra Pradesh</fullName>
                </value>
                <value>
                    <fullName>Arunachal Pradesh</fullName>
                </value>
                <value>
                    <fullName>Assam</fullName>
                </value>
                <value>
                    <fullName>Bihar</fullName>
                </value>
                <value>
                    <fullName>Chhattisgarh</fullName>
                </value>
                <value>
                    <fullName>Goa</fullName>
                </value>
                <value>
                    <fullName>Gujarat</fullName>
                </value>
                <value>
                    <fullName>Haryana</fullName>
                </value>
                <value>
                    <fullName>Himachal Pradesh</fullName>
                </value>
                <value>
                    <fullName>Jharkhand</fullName>
                </value>
                <value>
                    <fullName>Karnataka</fullName>
                </value>
                <value>
                    <fullName>Kerala</fullName>
                </value>
                <value>
                    <fullName>Madhya Pradesh</fullName>
                </value>
                <value>
                    <fullName>Maharashtra</fullName>
                </value>
                <value>
                    <fullName>Manipur</fullName>
                </value>
                <value>
                    <fullName>Meghalaya</fullName>
                </value>
                <value>
                    <fullName>Mizoram</fullName>
                </value>
                <value>
                    <fullName>Odisha</fullName>
                </value>
                <value>
                    <fullName>Punjab</fullName>
                </value>
                <value>
                    <fullName>Rajasthan</fullName>
                </value>
                <value>
                    <fullName>Sikkim</fullName>
                </value>
                <value>
                    <fullName>Tamil Nadu</fullName>
                </value>
                <value>
                    <fullName>Telangana</fullName>
                </value>
                <value>
                    <fullName>Tripura</fullName>
                </value>
                <value>
                    <fullName>Uttarakhand</fullName>
                </value>
                <value>
                    <fullName>Uttar Pradesh</fullName>
                </value>
                <value>
                    <fullName>West Bengal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Approval Request</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/classes/TestApplyOrderOffers.cls
@isTest public with sharing class TestApplyOrderOffers {
    @isTest Public static void lineOffers(){
        //Getting Dealer Account
        Account dealerAccnt = TestDataFactory.createDealerAccount();
        
        //Getting Retailer Account
        Account retailerAccnt = TestDataFactory.createRetailerAccount(dealerAccnt.Id);
        
        //Creating Product
        Product2 prod = TestDataFactory.createProduct('Test Fruit Juice');
        
        //Creating standard pricebook
        Id standardPb = Test.getStandardPricebookId();
        
        //Creating PricebookEntry
        PricebookEntry standardPrice = TestDataFactory.createPricebookEntry(100,prod.Id);
        
        Id offerPerRecId = Schema.SObjectType.Scheme__c.getRecordTypeInfosByName().get('Percentage Discount').getRecordTypeId();
        
        Scheme__c offerPercentage =new Scheme__c(RecordTypeId=offerPerRecId,Name='Buy 1000 above Get 10% Off',Start_Date__c=system.today()-30,Active__c=True);
        insert offerPercentage;
        offerPercentage.Scheme_Type__c='Specific';
        offerPercentage.Order_Amount__c=10000;
        offerPercentage.Discount_Type__c='Percentage';
        offerPercentage.Discount_Percentage__c=10;   
        offerPercentage.End_Date__c=system.today()+20;
        offerPercentage.Header_Discount__c=True;
        offerPercentage.Status__c='Approved';
        offerPercentage.Active__c=true;
        offerPercentage.State__c='Telangana';
        update offerPercentage;
        
        System.debug('Percentage offer inserted is'+offerPercentage);
        Id orderRTRetlr = Schema.SObjectType.Order.getRecordTypeInfosByName().get('Retailer').getRecordTypeId();
        
        Order retailerOrder=new Order(AccountId=retailerAccnt.Id,recordTypeId=orderRTRetlr,Status='Draft',EffectiveDate=system.today()-5,Pricebook2Id =standardPb);
        insert retailerOrder;retailerOrder.Account__c=dealerAccnt.Id;update retailerOrder;       
        //System.debug('Id 2 is'+retailerOrder.PriceBook2Id);
        
        OrderItem i=new OrderItem(Product2Id=prod.Id,Quantity=100,OrderId=retailerOrder.id,UnitPrice=100,ListPrice=100,PricebookEntryId=standardPrice.id);
        //i.TotalPrice=i.Quantity*i.UnitPrice;
        //i.ListPrice=100;
        insert i;
        System.debug('total price is'+i.TotalPrice+'ret ord'+retailerOrder.TotalAmount);
        System.debug('inserted order id is'+i+'order is'+retailerOrder);
        system.debug('removing coupon');       
        Order OrdFields=[SELECT Discount_Amount__c FROM Order WHERE Id=:retailerOrder.id];
        // System.assertEquals('Buy 1000 above Get 10% Off', retailerOrder.Applied_Offer__c,'percentoffer');//Scheme__c	'Buy 1000 above,Get 10% Off'
        System.debug('discount amount is'+OrdFields.Discount_Amount__c);     
        System.assertEquals(1000,OrdFields.Discount_Amount__c);
        
    }
    @isTest Public static void AmountCheck(){
        System.debug('I am from amountceck');
        //Getting Dealer Account
        Account dealerAccnt = TestDataFactory.createDealerAccount();
        
        //Getting Retailer Account
        Account retailerAccnt = TestDataFactory.createRetailerAccount(dealerAccnt.Id);
        
        //Creating Product
        Product2 prod = TestDataFactory.createProduct('Test Fruit Juice');
        
        //Creating standard pricebook
        Id standardPb = Test.getStandardPricebookId();
        
        //Creating PricebookEntry
        PricebookEntry standardPrice = TestDataFactory.createPricebookEntry(100,prod.Id);
        
        System.debug('Id 3 is'+standardPrice.Pricebook2Id);
        
        Id offerPerRecId = Schema.SObjectType.Scheme__c.getRecordTypeInfosByName().get('Amount Discount').getRecordTypeId();
        
        Scheme__c offerAmount =new Scheme__c(RecordTypeId=offerPerRecId,Name='Buy1000aboveGet100back',Start_Date__c=system.today()-30,Active__c=True);
        insert offerAmount;
        offerAmount.End_Date__c=system.today()+30;
        offerAmount.Scheme_Type__c='Specific';
        offerAmount.Order_Amount__c=1000;
        offerAmount.Discount_Type__c='Amount';
        offerAmount.Discount_Amount__c=100;   
        //offerAmount.End_Date__c=system.today()+20;
        offerAmount.Header_Discount__c=True;
        offerAmount.Status__c='Approved';
        offerAmount.Active__c=true;
        offerAmount.State__c='Telangana';
        update offerAmount;
        
        System.debug('Percentage offer inserted is'+offerAmount);
        Id orderRTRetlr = Schema.SObjectType.Order.getRecordTypeInfosByName().get('Retailer').getRecordTypeId();
        
        Order retailerOrder=new Order(AccountId=retailerAccnt.Id,recordTypeId=orderRTRetlr,Status='Draft',EffectiveDate=system.today()-5,Pricebook2Id =standardPb);
        insert retailerOrder;retailerOrder.Account__c=dealerAccnt.Id;update retailerOrder;        
        //System.debug('Id 2 is'+retailerOrder.PriceBook2Id);
        
        OrderItem i=new OrderItem(Product2Id=prod.Id,Quantity=100,OrderId=retailerOrder.id,UnitPrice=100,ListPrice=100,PricebookEntryId=standardPrice.id);
        //i.TotalPrice=i.Quantity*i.UnitPrice;
        //i.ListPrice=100;
        insert i;
        Order OrdFields=[SELECT Discount_Amount__c FROM Order WHERE Id=:retailerOrder.id];
        
        
        System.debug('Percentage amount offer total price is'+i.TotalPrice+'ret ord'+retailerOrder.TotalAmount);
        System.debug('inserted order id is'+i+'order is'+retailerOrder);
        //System.assertEquals('Buy1000aboveGet100back',retailerOrder.Applied_Offer__c,'');//1000 above,Get 10% Off'
        
        System.assertEquals(100,OrdFields.Discount_Amount__c,'amountoffer');
        //System.debug('discount is 100');
    }
    @isTest Public static void CouponCheck(){
        //Getting Dealer Account
        Account dealerAccnt = TestDataFactory.createDealerAccount();
        
        //Getting Retailer Account
        Account retailerAccnt = TestDataFactory.createRetailerAccount(dealerAccnt.Id);
        
        //Creating Product
        Product2 prod = TestDataFactory.createProduct('Test Fruit Juice');
        
        //Creating standard pricebook
        Id standardPb = Test.getStandardPricebookId();
        
        //Creating PricebookEntry
        PricebookEntry standardPrice = TestDataFactory.createPricebookEntry(100,prod.Id);
        
        System.debug('Id 3 is'+standardPrice.Pricebook2Id);
        
        Coupon__c coup=new Coupon__c();
        coup.Active__c=true;
        coup.Name='Free FlightCoupon';
        coup.Valid_From__c=system.today()-10;
        coup.Valid_To__c=system.today()+30;
        insert coup;
        Id offerPerRecId = Schema.SObjectType.Scheme__c.getRecordTypeInfosByName().get('Promotional Offers').getRecordTypeId();
        //RecordType offerPerRecId = [SELECT Id FROM RecordType WHERE sObjectType = 'Offers__c' AND Name ='Percentage Discount'];
        
        Scheme__c offerAmount =new Scheme__c(RecordTypeId=offerPerRecId,Start_Date__c=system.today()-30,Active__c=True,Name='Buy100000getfreecoupon');
        insert offerAmount;
        offerAmount.End_Date__c=system.today()+30;
        offerAmount.Scheme_Type__c='Specific';
        offerAmount.Order_Amount__c=100000;
        offerAmount.Discount_Type__c='Coupon';
        offerAmount.Coupon__c=coup.id;
        offerAmount.Header_Discount__c=True;
        offerAmount.Status__c='Approved';
        offerAmount.Active__c=true;
        offerAmount.State__c='Telangana';
        update offerAmount;
        
        System.debug('Percentage offer inserted is'+offerAmount);
        Id orderRTRetlr = Schema.SObjectType.Order.getRecordTypeInfosByName().get('Retailer').getRecordTypeId();
        Order retailerOrder=TestDataFactory.createOrder(retailerAccnt.Id, orderRTRetlr);
        
        retailerOrder.Account__c=dealerAccnt.Id;update retailerOrder;        
        //System.debug('Id 2 is'+retailerOrder.PriceBook2Id);
        
        OrderItem i=new OrderItem(Product2Id=prod.Id,Quantity=1000,OrderId=retailerOrder.id,UnitPrice=100,ListPrice=100,PricebookEntryId=standardPrice.id);
        
        insert i;
        
        
        //system.debug('Percentage amount offer total price is'+i.TotalPrice+'ret ord'+retailerOrder.TotalAmount);
        //system.debug('inserted order id is'+i+'order is'+retailerOrder);
        Order OrdFields=[SELECT Applied_Offer__c FROM Order WHERE Id=:retailerOrder.id];
        System.assertEquals('Buy100000getfreecoupon', OrdFields.Applied_Offer__c,'couponoffer');//Scheme__c	'Buy 1000 above,Get 10% Off'
        System.debug('discount amount is'+retailerOrder.Discount_Amount__c);
        
    }
    @isTest Public static void NoOffer(){
        //Getting Dealer Account
        Account dealerAccnt = TestDataFactory.createDealerAccount();
        
        //Getting Retailer Account
        Account retailerAccnt = TestDataFactory.createRetailerAccount(dealerAccnt.Id);
        
        //Creating Product
        Product2 prod = TestDataFactory.createProduct('Test Fruit Juice');
        
        //Creating standard pricebook
        Id standardPb = Test.getStandardPricebookId();
        
        //Creating PricebookEntry
        PricebookEntry standardPrice = TestDataFactory.createPricebookEntry(100,prod.Id);
        
        System.debug('Id 3 is'+standardPrice.Pricebook2Id);
        
        Coupon__c coup=new Coupon__c();
        coup.Active__c=true;
        coup.Name='Free FlightCoupon';
        coup.Valid_From__c=system.today()-10;
        coup.Valid_To__c=system.today()+30;
        insert coup;
        Id offerPerRecId = Schema.SObjectType.Scheme__c.getRecordTypeInfosByName().get('Promotional Offers').getRecordTypeId();
        //RecordType offerPerRecId = [SELECT Id FROM RecordType WHERE sObjectType = 'Offers__c' AND Name ='Percentage Discount'];
        
        Scheme__c offerAmount =new Scheme__c(RecordTypeId=offerPerRecId,Start_Date__c=system.today()-30,Active__c=True,Name='Buy100000getfreecoupon');
        insert offerAmount;
        offerAmount.End_Date__c=system.today()+30;
        offerAmount.Scheme_Type__c='Specific';
        offerAmount.Order_Amount__c=100000;
        offerAmount.Discount_Type__c='Coupon';
        offerAmount.Coupon__c=coup.id;
        offerAmount.Header_Discount__c=True;
        offerAmount.Status__c='Approved';
        offerAmount.Active__c=true;
        offerAmount.State__c='Telangana';
        update offerAmount;
        
        System.debug('Percentage offer inserted is'+offerAmount);
        Id orderRTRetlr = Schema.SObjectType.Order.getRecordTypeInfosByName().get('Retailer').getRecordTypeId();
        Order retailerOrder=TestDataFactory.createOrder(retailerAccnt.Id, orderRTRetlr);
        
        retailerOrder.Account__c=dealerAccnt.Id;update retailerOrder;        
        //System.debug('Id 2 is'+retailerOrder.PriceBook2Id);
        
        OrderItem i=new OrderItem(Product2Id=prod.Id,Quantity=1000,OrderId=retailerOrder.id,UnitPrice=100,ListPrice=100,PricebookEntryId=standardPrice.id);
        
        insert i;
        i.Quantity=10;
        update i;
        
        //system.debug('Percentage amount offer total price is'+i.TotalPrice+'ret ord'+retailerOrder.TotalAmount);
        //system.debug('inserted order id is'+i+'order is'+retailerOrder);
        Order OrdFields=[SELECT Applied_Offer__c FROM Order WHERE Id=:retailerOrder.id];
        System.assertEquals(null, OrdFields.Applied_Offer__c,'couponoffer');//Scheme__c	'Buy 1000 above,Get 10% Off'
        System.debug('discount amount is'+retailerOrder.Discount_Amount__c);
        
    }
}