src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>For Dealer Accounts</description>
        <label>Dealer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Retailer</fullName>
        <active>true</active>
        <description>For Retailer Accounts</description>
        <label>Retailer</label>
    </recordTypes>
</CustomObject>

src/objects/Inventory__c.object
<CustomObject>
    <description>Inventory is used to manage warehouse stock activities,order related activities etc</description>
    <label>Inventory</label>
    <nameField>
        <displayFormat>INV-{00000}</displayFormat>
        <label>Inventory Id Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Dealer_Product_Price__c</fullName>
        <description>Product Price of Dealer Price Book</description>
        <label>Dealer Product Price</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Distributor__c</fullName>
        <label>Distributor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Inventories</relationshipLabel>
        <relationshipName>Inventories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>OnHand_Qty__c</fullName>
        <inlineHelpText>which is available at warehouse</inlineHelpText>
        <label>Quantity On Hand</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select the Related Pricebook</inlineHelpText>
        <label>Price Book</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Inventories</relationshipLabel>
        <relationshipName>Inventories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relationship with Product object to access product fields</description>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Inventories</relationshipLabel>
        <relationshipName>Inventories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Retailer_Price_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is retailer price book</description>
        <label>Retailer Price Book</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Inventories (Retailer Price Book)</relationshipLabel>
        <relationshipName>Inventories1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Retailer_Price__c</fullName>
        <description>Retailer price</description>
        <label>Retailer Product Price</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders (Account)</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <label>Dealer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Retailer</fullName>
        <active>true</active>
        <label>Retailer</label>
    </recordTypes>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Inventory__c</fullName>
        <label>Inventory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Stock</fullName>
                    <default>true</default>
                    <label>In Stock</label>
                </value>
                <value>
                    <fullName>Limited Availability</fullName>
                </value>
                <value>
                    <fullName>Out of Stock</fullName>
                </value>
                <value>
                    <fullName>On Backorder</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Max_Qty__c</fullName>
        <description>The Maximum Quantity of Products</description>
        <label>Maximum Qty</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Min_Qty__c</fullName>
        <description>The Minimum Quantity of Products</description>
        <label>Minimum Qty</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

force-app/main/default/classes/TestCheckProductInventory.cls
/*
* Author:- Somesh Mamidwar
* Created:- 17-09-2020
* Last Updated:- 
* Description:- Test Class for CheckProductInventory
*/
@isTest
public class TestCheckProductInventory {

    @isTest Public static void checkProdInv(){
        
         //Getting Dealer Account
        Account dealerAccnt = TestDataFactory.createDealerAccount();
        
        //Getting Retailer Account
        Account retailerAccnt = TestDataFactory.createRetailerAccount(dealerAccnt.Id);
        
        //Creating Product
        Product2 prod = TestDataFactory.createProduct('Test Fruit Juice');
        prod.Max_Qty__c=500;
        prod.Min_Qty__c=200;
        update prod;
        
        //standard pricebook
        Id standardPBook =Test.getStandardPricebookId();
        
        //Creating PricebookEntry
        PricebookEntry standardPrice = TestDataFactory.createPricebookEntry(100,prod.Id);
        
        //Inventory creation
        Inventory__c newInv=new Inventory__c();
        //insert newInv;        
        newInv.Distributor__c=dealerAccnt.id;
        newInv.OnHand_Qty__c=150;
        newInv.Product__c=prod.id;
        newInv.Price_Book__c=standardPBook;
        newInv.Dealer_Product_Price__c=standardPrice.UnitPrice;
        
        newInv.Retailer_Price_Book__c=standardPBook;
        newInv.Retailer_Price__c=standardPrice.UnitPrice;
        insert newInv;
        
         // Order creation
        Id orderRetailerRecTypId = Schema.SObjectType.Order.getRecordTypeInfosByName().get('Retailer').getRecordTypeId();
        Order retailerOrder=TestDataFactory.createOrder(retailerAccnt.Id, orderRetailerRecTypId);
        
        retailerOrder.Account__c=dealerAccnt.Id;
        update retailerOrder; 
        
        // Order Item Creation
		OrderItem retailerOi=new OrderItem(Product2Id=prod.Id,Quantity=100,OrderId=retailerOrder.id,UnitPrice=100,ListPrice=100,PricebookEntryId=standardPrice.id);       
        insert retailerOi;      
        
        CheckProductInventory.getOrderInventory(retailerOrder.Id);
        
        
        //Dealer  Order creation
        Id orderDealerRecTypId = Schema.SObjectType.Order.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
        Order dealerOrder=TestDataFactory.createOrder(dealerAccnt.Id, orderDealerRecTypId);
        
        // Order Item Creation
		OrderItem dealeroi=new OrderItem(Product2Id=prod.Id,Quantity=100,OrderId=dealerOrder.id,UnitPrice=100,ListPrice=100,PricebookEntryId=standardPrice.id);       
        insert dealeroi;  
        
        CheckProductInventory.getOrderInventory(dealerOrder.Id);
        
    }
    
}