src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>For Dealer Accounts</description>
        <label>Dealer</label>
    </recordTypes>
</CustomObject>

src/objects/Inventory__c.object
<CustomObject>
    <description>Inventory is used to manage warehouse stock activities,order related activities etc</description>
    <label>Inventory</label>
    <nameField>
        <displayFormat>INV-{00000}</displayFormat>
        <label>Inventory Id Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Dealer_Product_Price__c</fullName>
        <description>Product Price of Dealer Price Book</description>
        <label>Dealer Product Price</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Distributor__c</fullName>
        <label>Distributor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Inventories</relationshipLabel>
        <relationshipName>Inventories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>OnHand_Qty__c</fullName>
        <inlineHelpText>which is available at warehouse</inlineHelpText>
        <label>Quantity On Hand</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select the Related Pricebook</inlineHelpText>
        <label>Price Book</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Inventories</relationshipLabel>
        <relationshipName>Inventories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relationship with Product object to access product fields</description>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Inventories</relationshipLabel>
        <relationshipName>Inventories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Retailer_Price_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is retailer price book</description>
        <label>Retailer Price Book</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Inventories (Retailer Price Book)</relationshipLabel>
        <relationshipName>Inventories1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Retailer_Price__c</fullName>
        <description>Retailer price</description>
        <label>Retailer Product Price</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Inventory__c</fullName>
        <label>Inventory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Stock</fullName>
                    <default>true</default>
                    <label>In Stock</label>
                </value>
                <value>
                    <fullName>Limited Availability</fullName>
                </value>
                <value>
                    <fullName>Out of Stock</fullName>
                </value>
                <value>
                    <fullName>On Backorder</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Max_Qty__c</fullName>
        <description>The Maximum Quantity of Products</description>
        <label>Maximum Qty</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Min_Qty__c</fullName>
        <description>The Minimum Quantity of Products</description>
        <label>Minimum Qty</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

force-app/main/default/classes/TestSInventoryDetails.cls
@isTest
public class TestSInventoryDetails {

    @isTest Public static void getAccInvDetails(){
        
         //Getting Dealer Account
        Account dealerAccnt = TestDataFactory.createDealerAccount();
        
        //Creating Product
        Product2 prod = TestDataFactory.createProduct('Test Fruit Juice');
        prod.Max_Qty__c=500;
        prod.Min_Qty__c=200;
        update prod;
        
        //standard pricebook
        Id standardPBook =Test.getStandardPricebookId();
        
         Pricebook2 newPriceBook = new Pricebook2();
       	 newPriceBook.Name = 'Standard Price Book';
         newPriceBook.IsActive =true ;
         insert newPriceBook;
        
        //Creating PricebookEntry
        PricebookEntry standardPrice = TestDataFactory.createPricebookEntry(100,prod.Id);
        
      	/*PricebookEntry standardPrice = new PricebookEntry();  
        standardPrice.Pricebook2Id =newPriceBook.Id;
        standardPrice.Product2Id = prod.Id;
        standardPrice.UnitPrice = 100;
        standardPrice.IsActive = true;
        standardPrice.UseStandardPrice = false;
        insert standardPrice;*/
   
        //Inventory creation
        Inventory__c newInv=new Inventory__c();
        //insert newInv;        
        newInv.Distributor__c=dealerAccnt.id;
        newInv.OnHand_Qty__c=150;
        newInv.Product__c=prod.id;
        newInv.Price_Book__c=standardPBook;
        newInv.Dealer_Product_Price__c=standardPrice.UnitPrice;
        
        newInv.Retailer_Price_Book__c=standardPBook;
        newInv.Retailer_Price__c=standardPrice.UnitPrice;
        insert newInv;
        
		List <Inventory__c> getAccInvInv = sInventoryDetails.getAccInventoryDetails(dealerAccnt.id);
        
        List <Inventory__c> getQueryRetInv = sInventoryDetails.getQueryInvDetails(dealerAccnt.id,'Test Fruit Juice');
        
        
        
        sInventoryDetails.generateInvOrder(dealerAccnt.id,getQueryRetInv);
        
    }
    
}