src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>For Dealer Accounts</description>
        <label>Dealer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Retailer</fullName>
        <active>true</active>
        <description>For Retailer Accounts</description>
        <label>Retailer</label>
    </recordTypes>
</CustomObject>

src/objects/Inventory__c.object
<CustomObject>
    <description>Inventory is used to manage warehouse stock activities,order related activities etc</description>
    <label>Inventory</label>
    <nameField>
        <displayFormat>INV-{00000}</displayFormat>
        <label>Inventory Id Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Distributor__c</fullName>
        <label>Distributor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Inventories</relationshipLabel>
        <relationshipName>Inventories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>OnHand_Qty__c</fullName>
        <inlineHelpText>which is available at warehouse</inlineHelpText>
        <label>Quantity On Hand</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relationship with Product object to access product fields</description>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Inventories</relationshipLabel>
        <relationshipName>Inventories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Receivable_Qty__c</fullName>
        <label>Receivable Receipt</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Shipment_Quantity__c</fullName>
        <inlineHelpText>Enter the Quantity to be Shipped</inlineHelpText>
        <label>Planned Shipments</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Order_Type__c</fullName>
        <formula>Account.RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <label>Dealer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Retailer</fullName>
        <active>true</active>
        <label>Retailer</label>
    </recordTypes>
</CustomObject>

force-app/main/default/classes/SInventoryUpdate.cls
/*
 * Author:- Vamsi Alla
 * Created:- 28-08-2020
 * Last Updated:- 
 * Feature:- 
 * Description:- To Update an Inventory at Dealer account  on Order Creation
 */
public without sharing class SInventoryUpdate {

    public void updateInventory(List < Order > orderdata) {

        String sOrderAccId = '';
        List < Id > orderIds = new List < Id > ();
        List < Id > accIds = new List < Id > ();
        List < Id > distributorIds = new List < Id > ();
        List < Id > invProdIds = new List < Id > ();
        List < OrderItem > orderItems = new List < OrderItem > ();
        List < OrderItem > relatedOrderItems = new List < OrderItem > ();
        List < Inventory__c > invItems = new List < Inventory__c > ();
        Map < Id, Account > accDetails = new Map < Id, Account > ();
        Map < Id, OrderItem > ordProdDetails = new Map < Id, OrderItem > ();

        for (Order order: orderdata) {
            accIds.add(order.AccountId);
            orderIds.add(order.Id);
        }

        if (Schema.sObjectType.Account.fields.ParentId.isReadable()) {
            accDetails = [Select Id, ParentId from Account where Id in: accIds];
        }

        for (Order order: orderdata) {
            if (accDetails.get(order.AccountId).ParentId != null) {
                distributorIds.add(accDetails.get(order.AccountId).ParentId);
            } else {
                distributorIds.add(accDetails.get(order.AccountId).Id);
            }
        }

        if (Schema.sObjectType.OrderItem.fields.Product2Id.isReadable() && Schema.sObjectType.OrderItem.fields.Quantity.isReadable()) {
            orderItems = [SELECT Id, Quantity, Product2Id FROM OrderItem WHERE OrderId in: orderIds];
        }

        for (OrderItem oi: orderItems) {
            invProdIds.add(oi.Product2Id);
            ordProdDetails.put(oi.Product2Id, oi);
        }

        if (Schema.sObjectType.Inventory__c.fields.Product__c.isReadable() && Schema.sObjectType.Shipment_Quantity__c.fields.Product__c.isReadable()) {
            invItems = [SELECT Id, Product__c, Distributor__c, Shipment_Quantity__c FROM Inventory__c WHERE Product__c in: InvProdIds];
        }

        for (Order order: orderdata) {
            //Get Order Related OrderItems
            for (OrderItem oi: orderItems) {
                if (oi.Order == order.Id) {
                    relatedOrderItems.add(oi);
                }
            }

            for (OrderItem oi: relatedOrderItems) {
                for (Inventory__c inv: invItems) {
                    if (inv.Distributor__c == order.Account && inv.Product__c == oi.Product2Id) {
                        if (order.Order_Type__c == 'Retailer') {
                            if (order.Status == 'Booked') {
                                Decimal qty = ordProdDetails.get(inv.Product__c).Quantity;
                                inv.Shipment_Quantity__c += qty;
                            } else if (order.Status == 'Out For Delivery') {
                                Decimal qty = ordProdDetails.get(inv.Product__c).Quantity;
                                inv.Shipment_Quantity__c -= qty;
                                inv.OnHand_Qty__c -= qty;
                            } else {
                                continue;
                            }
                        } else if (order.Order_Type__c == 'Distributor') {
                            if (order.Status == 'Confirmed') {
                                Decimal qty = ordProdDetails.get(inv.Product__c).Quantity;
                                System.debug('Order Item Qty..:' + qty);
                                inv.Receivable_Qty__c += qty;
                            } else if (order.Status == 'Delivered') {
                                Decimal qty = ordProdDetails.get(inv.Product__c).Quantity;
                                inv.Receivable_Qty__c -= qty;
                                inv.OnHand_Qty__c += qty;
                            } else {
                                continue;
                            }
                        }
                    } else {
                        continue;
                    }
                }
            }
        }

        if (invItems.size() > 0) {
            if (Schema.sObjectType.Inventory__c.fields.OnHand_Qty__c.isUpdateable() &&
                Schema.sObjectType.Inventory__c.fields.Receivable_Qty__c.isUpdateable() &&
                Schema.sObjectType.Inventory__c.fields.Shipment_Quantity__c.isUpdateable()) {
                update invItems;
            }
        }
    }
}