src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Partner_Dealer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Dealer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <sharingModel>ReadWriteTransfer</sharingModel>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scheme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Scheme</label>
        <referenceTo>Scheme__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Applied_Scheme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applied Scheme</label>
        <referenceTo>Scheme__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Dealer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Dealer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Order/fields/Scheme__c.field-meta.xml
<CustomField>
    <fullName>Scheme__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Scheme</label>
    <referenceTo>Scheme__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Scheme__c.object
<CustomObject>
    <label>Scheme</label>
    <nameField>
        <label>Scheme Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schemes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SCaseHelper.cls
public with sharing class SCaseHelper{
public void sCaseTgrHelperClass(List<Case> caseData)
{
//List < Id > caseIds = new List < Id > ();
List< Order> listOrd = new List<Order>();//[select AccountId,Applied_Scheme__c from Order where Id in: orderIds];
List < Id > orderIds = new List < Id > ();
for (Case cas: CaseData) {
orderIds.add(cas.Order__c);
//caseIds.add(cas.Id);
}

if (
    Order.SObjectType.getDescribe().isAccessible() && Schema.SObjectType.Order.fields.Applied_Scheme__c.isAccessible()&& Schema.SObjectType.Order.fields.AccountId.isAccessible()
) {
    // Defining a List object of Parent Accounts to store 
    //List < Account > parentAccList = [Select Id, Partner_Dealer__c from Account where Id in: parAccntIds];
    //List<Order>
    listOrd = [select AccountId,Applied_Scheme__c from Order where Id in: orderIds];
}
// Defining a Map object to store a key,value pair of child and Parent Accounts
Map<Id, Order> mapParentOrder = new Map<Id, Order>();
for (Order o : listOrd) {
    mapParentOrder.put(o.Id,o);
}
List<Case> v1 = caseData;
for(Case cases : v1) {  

if(cases.Order__c != null){
    Order ord = mapParentOrder.Get(cases.Order__c);

cases.AccountId = ord.AccountId;
if(cases.Scheme__c == null){
    if(ord.Applied_Scheme__c != null) {
        cases.Scheme__c= ord.Applied_Scheme__c;                    
    }  
}
}
}
}
}