src/objects/Coupon__c.object
<CustomObject>
    <label>Coupon</label>
    <nameField>
        <label>Coupon Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coupons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders (Account)</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Applied_Scheme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applied Scheme</label>
        <referenceTo>Scheme__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Coupon_Id__c</fullName>
        <label>Coupon Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Discount_Amount__c</fullName>
        <label>Discount Amount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Header_Discount__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Header Discount</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order_Type__c</fullName>
        <formula>Account.RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Promotional_Scheme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Promotional Scheme</label>
        <referenceTo>Promotional_Offer__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Retailer</fullName>
        <active>true</active>
        <label>Retailer</label>
    </recordTypes>
</CustomObject>

force-app/main/default/objects/Order/fields/Applied_Offer__c.field-meta.xml
<CustomField>
    <fullName>Applied_Offer__c</fullName>
    <label>Applied Offer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Scheme__c.field-meta.xml
<CustomField>
    <fullName>Scheme__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Scheme</label>
    <referenceTo>Scheme__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Promotional_Offer__c.object
<CustomObject>
    <label>Promotional Offer</label>
    <nameField>
        <displayFormat>AMCUPON-{0000}</displayFormat>
        <label>Promotional Offer</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotional Offers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Promotional Offers</relationshipLabel>
        <relationshipName>Promotional_Offers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Coupon__c</fullName>
        <label>Coupon</label>
        <referenceTo>Coupon__c</referenceTo>
        <relationshipLabel>Promotional Offers</relationshipLabel>
        <relationshipName>Promotional_Offers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

src/objects/Scheme__c.object
<CustomObject>
    <label>Scheme</label>
    <nameField>
        <label>Scheme Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schemes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Coupon__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Coupon</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Coupon__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Coupon__c.Valid_From__c</field>
                <operation>lessOrEqual</operation>
                <valueField>$Source.CreatedDate</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Coupon__c</referenceTo>
        <relationshipLabel>Schemes</relationshipLabel>
        <relationshipName>Schemes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Discount_Amount__c</fullName>
        <label>Discount Amount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Discount_Percentage__c</fullName>
        <label>Discount Percentage</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Discount_Type__c</fullName>
        <label>Discount Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Amount</fullName>
                    <default>true</default>
                    <label>Amount</label>
                </value>
                <value>
                    <fullName>Percentage</fullName>
                </value>
                <value>
                    <fullName>Quantity</fullName>
                </value>
                <value>
                    <fullName>Coupon</fullName>
                </value>
                <value>
                    <fullName>Cross Product Offer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Header_Discount__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Header Discount</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order_Amount__c</fullName>
        <label>Order Amount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Scheme_Type__c</fullName>
        <label>Scheme Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Generic</fullName>
                </value>
                <value>
                    <fullName>Specific</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Andhra Pradesh</fullName>
                </value>
                <value>
                    <fullName>Arunachal Pradesh</fullName>
                </value>
                <value>
                    <fullName>Assam</fullName>
                </value>
                <value>
                    <fullName>Bihar</fullName>
                </value>
                <value>
                    <fullName>Chhattisgarh</fullName>
                </value>
                <value>
                    <fullName>Goa</fullName>
                </value>
                <value>
                    <fullName>Gujarat</fullName>
                </value>
                <value>
                    <fullName>Haryana</fullName>
                </value>
                <value>
                    <fullName>Himachal Pradesh</fullName>
                </value>
                <value>
                    <fullName>Jharkhand</fullName>
                </value>
                <value>
                    <fullName>Karnataka</fullName>
                </value>
                <value>
                    <fullName>Kerala</fullName>
                </value>
                <value>
                    <fullName>Madhya Pradesh</fullName>
                </value>
                <value>
                    <fullName>Maharashtra</fullName>
                </value>
                <value>
                    <fullName>Manipur</fullName>
                </value>
                <value>
                    <fullName>Meghalaya</fullName>
                </value>
                <value>
                    <fullName>Mizoram</fullName>
                </value>
                <value>
                    <fullName>Odisha</fullName>
                </value>
                <value>
                    <fullName>Punjab</fullName>
                </value>
                <value>
                    <fullName>Rajasthan</fullName>
                </value>
                <value>
                    <fullName>Sikkim</fullName>
                </value>
                <value>
                    <fullName>Tamil Nadu</fullName>
                </value>
                <value>
                    <fullName>Telangana</fullName>
                </value>
                <value>
                    <fullName>Tripura</fullName>
                </value>
                <value>
                    <fullName>Uttarakhand</fullName>
                </value>
                <value>
                    <fullName>Uttar Pradesh</fullName>
                </value>
                <value>
                    <fullName>West Bengal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/classes/ApplyOrderOffers.cls
/*
* Author:- Vamsi Alla
* Created:- 31-08-2020
* Last Updated:-  
* Description:- Craete for Schemes applicable on Order
*/
public without sharing class ApplyOrderOffers {
    
    List<Scheme__c> offers = new List<Scheme__c>();
    List<Promotional_Offer__c> issuedCoupons = new List<Promotional_Offer__c>();
    Map<Id,Promotional_Offer__c> issuedCouponsMap = new Map<Id,Promotional_Offer__c>();

    String offerFields = '';
    public ApplyOrderOffers() {
        offerFields = GetAllFields.getAllObjectField('Scheme__c');
        String query = 'select ' + offerFields + ' from Scheme__c where active__c = True AND Start_Date__c <= Today and (End_Date__c = null OR End_Date__c >= Today) and Header_Discount__c = True';
        offers = Database.query(query);
    }

    public void applyOffers(Order order){
        String appliedOffer = '';
        String appliedOfferId = '';
        Decimal discountAmount = 0;
        Decimal discount = 0;
        Boolean qualify = false;
        Boolean couponApplied = false;
        String couponId = '';

      //  for(Order order : orders.values()){
           if(order.Order_Type__c == 'Retailer' && order.TotalAmount > 0){
                discountAmount = 0;
                qualify = false;
                for(Scheme__c offer : offers){
                    discount = 0;
                    
                    if(offer.Scheme_Type__c == 'Specific'){
                        if(offer.State__c != null){
                            String[] states = offer.State__c.split(';');
                            for(String state : states){
                                if (state == order.shippingstate){
                                    qualify = true;
                                }
                            }
                        }
                        if(offer.Order_Amount__c != null){
                            if(order.TotalAmount >= offer.Order_Amount__c){
                                qualify = true;
                            }else{
                                qualify = false;
                            }
                        }
                    }else{
                        qualify = true;
                    }

                    if(offer.Discount_Type__c == 'Amount' && qualify && !couponApplied){
                        discount = offer.Discount_Amount__c;
                        if(discount > discountAmount){
                            discountAmount = discount;
                            appliedOffer = offer.Name;
                            appliedOfferId = offer.Id;
                        }
                    }else if(offer.Discount_Type__c == 'Percentage' && qualify && !couponApplied){
                        discount = order.TotalAmount * (offer.Discount_Percentage__c/100);
                        if(discount > discountAmount){
                            discountAmount = discount;
                            appliedOffer = offer.Name;
                            appliedOfferId = offer.Id;
                        }
                    }else if(offer.Discount_Type__c == 'Coupon' && qualify && !couponApplied){
                        couponId = offer.Coupon__c;
                        appliedOffer = offer.Name;
                        appliedOfferId = offer.Id;
                        couponApplied = true;
                    }else {
                        //do nothing
                    }
                
                    if(couponId != ''){
                        if(order.Coupon_Id__c == null && order.Promotional_Scheme__c == null){
                            order.Coupon_Id__c = couponId;
                            Id accountId = order.accountId;
                            Promotional_Offer__c isscoupon = new Promotional_Offer__c();
                            isscoupon.Account__c = accountId;
                            isscoupon.Coupon__c = couponId;
                         
                            insert isscoupon;
                            
                            order.Promotional_Scheme__c = isscoupon.Id;
                        }
                        discountAmount = 0;
                    }else if(order.Promotional_Scheme__c != null){
                        order.Coupon_Id__c = null;
                        List<Promotional_Offer__c> coupReff = new List<Promotional_Offer__c>();
                        Id coupReffId = order.Promotional_Scheme__c;
                        if(Promotional_Offer__c.SObjectType.getDescribe().isAccessible() ){
                         coupReff = [Select Id from Promotional_Offer__c where Id =:coupReffId];
                        }
                        delete coupReff;
                        order.Promotional_Scheme__c = null;
                    }else{
                        // do nothing
                    }
                    if(appliedOfferId != ''){
                        order.Applied_Scheme__c = appliedOfferId;
                    }else{
                        order.Applied_Scheme__c = null;
                    }
                    order.Discount_Amount__c = discountAmount;
                    order.Applied_Offer__c = appliedOffer;
                    if(appliedOffer != ''){
                        order.Header_Discount__c = true;
                    }else{
                        order.Header_Discount__c = false;
                    }
                }
            }
       // }
    }
}