src/objects/Inventory__c.object
<CustomObject>
    <description>Inventory is used to manage warehouse stock activities,order related activities etc</description>
    <label>Inventory</label>
    <nameField>
        <displayFormat>INV-{00000}</displayFormat>
        <label>Inventory Id Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relationship with Product object to access product fields</description>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Inventories</relationshipLabel>
        <relationshipName>Inventories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Retailer_Price_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is retailer price book</description>
        <label>Retailer Price Book</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Inventories (Retailer Price Book)</relationshipLabel>
        <relationshipName>Inventories1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Retailer_Price__c</fullName>
        <description>Retailer price</description>
        <label>Retailer Product Price</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Inventory__c</fullName>
        <label>Inventory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Stock</fullName>
                    <default>true</default>
                    <label>In Stock</label>
                </value>
                <value>
                    <fullName>Limited Availability</fullName>
                </value>
                <value>
                    <fullName>Out of Stock</fullName>
                </value>
                <value>
                    <fullName>On Backorder</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/classes/SInventoryTriggerHandler.cls
/*
* Author:- Somesh Mamidwar
* Created:- 28-08-2020
* Last Updated:- 
* Description:-  InventoryTriggerHandler Class
*/
public without sharing class SInventoryTriggerHandler {

    public void sInventoryTrgInsertHelper(Inventory__c inventoryData) {

         List<PricebookEntry> pbe = new List<PricebookEntry>();
         if (Schema.sObjectType.PricebookEntry.fields.UnitPrice.isAccessible()){
            pbe  = [Select PriceBook2.Name, Product2.Id, Product2.Name, UnitPrice, Name From PricebookEntry 
              WHERE  PriceBook2.Id = :inventoryData.Retailer_Price_Book__c  AND Product2.Id = :inventoryData.Product__c limit 1 ];
         }

            if(!pbe.isEmpty()) {
             inventoryData.Retailer_Price__c = pbe[0].UnitPrice;
            }
         

     }
 
     public void sInventoryTrgUpdateHelper(Inventory__c invNew ,Inventory__c oldinv) {
        
        List<PricebookEntry> pbe = new List<PricebookEntry>();

             if (Schema.sObjectType.PricebookEntry.fields.UnitPrice.isAccessible()){
               pbe  = [Select PriceBook2.Name, Product2.Id, Product2.Name, UnitPrice, Name From PricebookEntry 
                  WHERE  PriceBook2.Id = :invNew.Retailer_Price_Book__c  AND Product2.Id = :invNew.Product__c limit 1 ];
             }

             if(!pbe.isEmpty()) {           
                 invNew.Retailer_Price__c = pbe[0].UnitPrice;  
             }                    
 
         }
 }