src/objects/Order.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Credit_Remaining__c</fullName>
        <formula>Account.Available_Credit__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Credit Remaining</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Line_Discount__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Line Discount</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <label>Dealer</label>
    </recordTypes>
</CustomObject>

force-app/main/default/objects/Order/fields/Applied_Offer__c.field-meta.xml
<CustomField>
    <fullName>Applied_Offer__c</fullName>
    <label>Applied Offer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>Applied_Offer__c</fullName>
        <label>Applied Offer</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Record_Type__c</fullName>
        <formula>Order.Order_Type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Order Record Type</label>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/classes/SOrderItemTriggerHandler.cls
public with sharing class SOrderItemTriggerHandler {

    public void sOrderTrgIsBeforeHelper(List<OrderItem> ordItemData){
        Decimal orderTotal = 0;
        Decimal creditremaing = 0;
        Set<Id> orderIds = new Set<Id>(); 

        for (OrderItem oi : ordItemData) {
            if (oi.orderid != null) {
                orderIds.add(oi.orderid);
            }
        }

        Map<Id, Order> orders = new Map<Id, Order>(
             [select id,Credit_Remaining__c from Order where id in :orderIds]
        );

        for (OrderItem orderitem : ordItemData) {
            if(orderitem.Order_Record_Type__c == 'Dealer'){ 
                Order ord = orders.get(orderitem.orderid);
                creditremaing = ord.Credit_Remaining__c;
                for(OrderItem orditem : ordItemData){
                    if(orderitem.orderid == orditem.orderid){
                        orderTotal += orditem.UnitPrice * orditem.Quantity;
                    }
                }
                if(orderTotal > creditremaing){
                    orderitem.adderror('You will not able to proceed with this Order. As your order value is greater than your Credit Available.');
                }
            }
        }

    }

    public void sOrderTrgIsAfterHelper(List<OrderItem> ordNewData,List<OrderItem> ordOldData){

        Set<Id> orderIds = new Set<Id>();

        if(ordOldData != null) {
            for(OrderItem oi: ordOldData) {
                orderIds.add(oi.orderid);
            }
        }

        if(ordNewData != null) {
            for(OrderItem oi: ordNewData) {
                orderIds.add(oi.orderid);
            }
        }

        Map<Id, Order> orders = new Map<Id, Order>(
            [select id, Line_Discount__c from Order where id in :orderIds]
        );

        for (OrderItem orderitem : ordNewData) {
            if(orderitem.Applied_Offer__c  != null){
                Order ord = orders.get(orderitem.orderid);
                ord.Line_Discount__c = true;
            }else{
                Order ord = orders.get(orderitem.orderid);
                ord.Line_Discount__c = false;
            }
        }
        update orders.values(); 

    }

}