src/objects/Order.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Applied_Scheme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applied Scheme</label>
        <referenceTo>Scheme__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Discount_Amount__c</fullName>
        <label>Discount Amount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Header_Discount__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Header Discount</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Retailer</fullName>
        <active>true</active>
        <label>Retailer</label>
    </recordTypes>
</CustomObject>

force-app/main/default/objects/Order/fields/Applied_Offer__c.field-meta.xml
<CustomField>
    <fullName>Applied_Offer__c</fullName>
    <label>Applied Offer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Scheme__c.field-meta.xml
<CustomField>
    <fullName>Scheme__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Scheme</label>
    <referenceTo>Scheme__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>Applied_Offer__c</fullName>
        <label>Applied Offer</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Applied_Scheme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applied Scheme</label>
        <referenceTo>Scheme__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cross_Discount_Product_Id__c</fullName>
        <label>Cross Discount Product Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Discount_Amount__c</fullName>
        <label>Discount Amount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Offered_Quantity__c</fullName>
        <label>Offered Quantity</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Order_Record_Type__c</fullName>
        <formula>Order.Order_Type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Order Record Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipping__c</fullName>
        <formula>Order.ShippingState</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Shipping</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Scheme__c.object
<CustomObject>
    <label>Scheme</label>
    <nameField>
        <label>Scheme Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schemes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Buy__c</fullName>
        <label>Buy</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Discount_Amount__c</fullName>
        <label>Discount Amount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Discount_Type__c</fullName>
        <label>Discount Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Amount</fullName>
                    <default>true</default>
                    <label>Amount</label>
                </value>
                <value>
                    <fullName>Percentage</fullName>
                </value>
                <value>
                    <fullName>Quantity</fullName>
                </value>
                <value>
                    <fullName>Coupon</fullName>
                </value>
                <value>
                    <fullName>Cross Product Offer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Get_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Get Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Schemes (Get Product)</relationshipLabel>
        <relationshipName>Schemes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Get__c</fullName>
        <label>Get</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Header_Discount__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Header Discount</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order_Amount__c</fullName>
        <label>Order Amount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Schemes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scheme_Type__c</fullName>
        <label>Scheme Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Generic</fullName>
                </value>
                <value>
                    <fullName>Specific</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Andhra Pradesh</fullName>
                </value>
                <value>
                    <fullName>Arunachal Pradesh</fullName>
                </value>
                <value>
                    <fullName>Assam</fullName>
                </value>
                <value>
                    <fullName>Bihar</fullName>
                </value>
                <value>
                    <fullName>Chhattisgarh</fullName>
                </value>
                <value>
                    <fullName>Goa</fullName>
                </value>
                <value>
                    <fullName>Gujarat</fullName>
                </value>
                <value>
                    <fullName>Haryana</fullName>
                </value>
                <value>
                    <fullName>Himachal Pradesh</fullName>
                </value>
                <value>
                    <fullName>Jharkhand</fullName>
                </value>
                <value>
                    <fullName>Karnataka</fullName>
                </value>
                <value>
                    <fullName>Kerala</fullName>
                </value>
                <value>
                    <fullName>Madhya Pradesh</fullName>
                </value>
                <value>
                    <fullName>Maharashtra</fullName>
                </value>
                <value>
                    <fullName>Manipur</fullName>
                </value>
                <value>
                    <fullName>Meghalaya</fullName>
                </value>
                <value>
                    <fullName>Mizoram</fullName>
                </value>
                <value>
                    <fullName>Odisha</fullName>
                </value>
                <value>
                    <fullName>Punjab</fullName>
                </value>
                <value>
                    <fullName>Rajasthan</fullName>
                </value>
                <value>
                    <fullName>Sikkim</fullName>
                </value>
                <value>
                    <fullName>Tamil Nadu</fullName>
                </value>
                <value>
                    <fullName>Telangana</fullName>
                </value>
                <value>
                    <fullName>Tripura</fullName>
                </value>
                <value>
                    <fullName>Uttarakhand</fullName>
                </value>
                <value>
                    <fullName>Uttar Pradesh</fullName>
                </value>
                <value>
                    <fullName>West Bengal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/classes/ApplyOrderLineOffers.cls
/*
* Author:- Vamsi Alla
* Created:- 31-08-2020
* Last Updated:- 
* Description:- Created for Quantity Schemes
*/
public without sharing class ApplyOrderLineOffers {
    
    List<Scheme__c> offers = new List<Scheme__c>();
    String offerFields = '';
    
    public ApplyOrderLineOffers() {
        offerFields = GetAllFields.getAllObjectField('Scheme__c');
        String query = 'select ' + offerFields + ' from Scheme__c where active__c = True AND Start_Date__c <= Today AND (End_Date__c = null OR End_Date__c >= Today) and Header_Discount__c = False';
        offers = Database.query(query);
    }
    
    public void applyOffers(OrderItem orderitem){
        String appliedOffer = '';
        String appliedOfferId = '';
        Decimal discountAmount = 0;
        Decimal discount = 0;
        Boolean qualify = false;
        Boolean qtyApplied = false;
        Decimal unitPrice = 0;
        Decimal freeQty = 0;
        Boolean qtyDiscApplied = false;
        
            if(orderitem != null && orderitem.Order_Record_Type__c == 'Retailer'){
                discountAmount = 0;
                for(Scheme__c offer : offers){
                    discount = 0;
                    if(offer.Scheme_Type__c == 'Specific'){
                        if(offer.State__c != null){
                            String[] states = offer.State__c.split(';');
                            for(String state : states){
                                if (state == orderitem.Shipping__c){
                                    qualify = true;
                                }
                            }
                        }
                        if(offer.Order_Amount__c != null){
                            if(orderitem.TotalPrice >= offer.Order_Amount__c){
                                qualify = true;
                            }else{
                                qualify = false;
                            }
                        }
                        if(offer.Product__c != null){
                            if(orderitem.Product2Id == offer.Product__c){
                                qualify = true;
                            }else{
                                qualify = false;
                            }
                        }
                    }else{
                        qualify = true;
                    }
  					 if(offer.Discount_Type__c == 'Quantity' && qualify){
                        if(offer.Buy__c <= orderitem.Quantity){
                            discount = offer.Get__c * orderitem.UnitPrice;
                            
                            if(discount > discountAmount){   
                                Decimal totalunits = orderitem.Quantity + offer.Get__c;
                                if(orderitem.ListPrice != null){
                                    unitPrice = (orderitem.ListPrice * orderitem.Quantity) / totalunits;
                                }else{
                                    unitPrice = (orderitem.UnitPrice * orderitem.Quantity) / totalunits;
                                }
                                orderitem.Quantity = totalunits;
                                discountAmount = discount;
                                appliedOffer = offer.Name;
                                appliedOfferId = offer.Id;
                                qtyDiscApplied = true;
                                freeQty = offer.Get__c;
                            }
                        }
                    }else if(offer.Discount_Type__c == 'Cross Product Offer' && qualify){
                        if(offer.Buy__c <= orderitem.Quantity){
                            if(orderitem.Cross_Discount_Product_Id__c == null){

                                List<Order> order = new List<Order>();
                                Decimal qty = offer.Get__c;
                                String product2Id = offer.Get_Product__c;
                             
                                order = [Select Id,Pricebook2Id from Order where Id =: orderitem.OrderId]; 
                                
                                String priceBookId = order[0].Pricebook2Id;
                                String orderId = order[0].Id;
                               
                                PricebookEntry[] pbe = [Select Id,UnitPrice from PricebookEntry where Pricebook2Id =:priceBookId AND Product2Id =:product2Id];
                                
                                if(pbe.size() > 0){
                                    String priceBookEntryId = pbe[0].Id;
                                    List <OrderItem> ordItm = new List<OrderItem>();
                                    if(Schema.SObjectType.OrderItem.fields.Id.isAccessible()){
                                     ordItm = [Select Id from OrderItem where orderId =:orderId AND PricebookEntryId =:priceBookEntryId];
                                    }
                                    if(ordItm.size() > 0){  
                                        ordItm[0].Quantity = qty;
                                        update ordItm[0];
                                    }else{
                                        OrderItem ordItem = new OrderItem();
                                        ordItem.OrderId = orderitem.OrderId;
                                        ordItem.PricebookEntryId = pbe[0].Id;
                                        ordItem.Product2Id = product2Id;
                                        ordItem.UnitPrice = 0.00;
                                        ordItem.Quantity = qty;

                                        insert ordItem;
                                        
                                        orderitem.Cross_Discount_Product_Id__c = ordItem.Id;
                                    }
                                    appliedOffer = offer.Name;
                                    appliedOfferId = offer.Id;
                                }
                            }
                        }else{
                            if(orderitem.Cross_Discount_Product_Id__c != null){
                                String sPromoProductId = orderitem.Cross_Discount_Product_Id__c;
                                List<OrderItem> ordItemdel = new List<OrderItem>();
                                if(Schema.SObjectType.OrderItem.fields.Id.isAccessible() ){
                                 ordItemdel = [Select id from OrderItem where Id =: sPromoProductId];
                                }
                            
                                delete ordItemdel;
                                
                                orderitem.Cross_Discount_Product_Id__c = null;
                                appliedOffer = null;
                                appliedOfferId = null;
                            }
                        }
                    }else {
                        //do nothing
                    }
                }
                if(qtyDiscApplied == true){
                    orderitem.Offered_Quantity__c = freeQty;
                }else{
                    orderitem.Offered_Quantity__c = 0;
                }
                if(unitPrice > 0){
                    orderitem.UnitPrice = unitPrice;
                }
                if(appliedOfferId != ''){
                    orderitem.Applied_Scheme__c = appliedOfferId;
                }else{
                    orderitem.Applied_Scheme__c = null;
                }
                orderitem.Discount_Amount__c = discountAmount;
                orderitem.Applied_Offer__c = appliedOffer;
            }
        
    }
}